name: NuGet vulnerabilities

on:
  schedule:
    - cron: "0 0 * * 1-5"
  
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  nuget-vulnerabilities:
    name: NuGet vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-dotnet@v3.0.3
      - run: ./build/nuget_vulnerabilities.sh
