name: Release Paperless

on:
  push:
    tags: [ v*.*.** ]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-dotnet@v4.0.0
      - id: publish
        run: ./build/pack.sh "${{ github.ref_name }}" "${{ github.run_number }}"

      - name: NuGet Push
        run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: ${{ steps.publish.outputs.publish-directory }}

      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          prerelease: false
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ${{ steps.publish.outputs.publish-directory }}/**/*.nupkg
