name: Run tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - run: ./build/test.sh

      - name: Gather Code Coverage
        if: github.event.schedule == null
        uses: codecov/codecov-action@v4.0.1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  resharper:
    name: Resharper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.3.1
      - run: ./build/build.sh

      - name: ReSharper annotations
        uses: VMelnalksnis/resharper-inspect-action@v0.3.0
        with:
          solution: Testcontainers.sln
          resharper-version: 2023.3.2
          treat-warnings-as-errors: true
